name: Bug Report
description: Report a bug or issue with the project.
title: "[Bug]: "
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following details to help us address the issue effectively.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A clear and concise description of what the bug is. Include the expected vs. actual behavior."
      placeholder: "Explain the issue and how it deviates from expected behavior."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "List all steps needed to reproduce the bug. Include as much detail as possible."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "Describe what you expected to happen."
      placeholder: "Explain the desired outcome."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Provide details about your environment, such as OS, browser, and versions."
      placeholder: |
        - OS: [e.g., macOS, Windows]
        - Browser: [e.g., Chrome, Firefox, Safari]
        - Node.js version: [e.g., 16.17.0]
        - Yarn version: [e.g., 1.22.19]
        - Any other relevant details
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Add any other context about the problem, such as logs or error messages."
      placeholder: "Include logs, error messages, or other context here."
  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, provide a link to screenshots to help explain the issue."
      placeholder: "Attach or provide URLs to screenshots."
